# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      #<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "tank/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "tank/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "tank/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/6ED3-A328";
      fsType = "vfat";
    };

  fileSystems."/data" =
    {
      device = "data";
      fsType = "zfs";
    };

  fileSystems."/data/enc" =
    {
      device = "data/enc";
      fsType = "zfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/eac63f5f-b378-4080-8fb8-6f64b94062cc"; }];

  nix.maxJobs = lib.mkDefault 8;
}
